import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { SessionProvider } from '@/components/SessionProvider';
import NavBar from '@/components/NavBar';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Progress',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <SessionProvider>
                    <div className="flex flex-col h-screen bg-zinc-50 font-sans dark:bg-black">
                        <div className="min-h-24 border-0">
                            <NavBar />
                        </div>
                        <div className="flex-1 min-h-0 border-0 overflow-hidden">
                            {children}
                        </div>
                    </div>
                </SessionProvider>
            </body>
        </html>
    );
}
